### ISSUE TITLE
Cannot find module './prism-markdown'

### ISSUE THREAD

**Issue by VaguelyCloud** [gera2ld/markmap#74]
An error will be reported when there are code blocks in the markdown file，please,thinks

(node:12803) UnhandledPromiseRejectionWarning: Error: Cannot find module './prism-markdown'
Require stack:
- /usr/local/lib/node_modules/markmap-cli/dist/index.js
- /usr/local/lib/node_modules/markmap-cli/bin/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at /usr/local/lib/node_modules/markmap-cli/dist/index.js:14952:34
    at handleId (/usr/local/lib/node_modules/markmap-cli/dist/index.js:14723:17)
    at loadComponentsInOrder (/usr/local/lib/node_modules/markmap-cli/dist/index.js:14748:7)
    at Object.load (/usr/local/lib/node_modules/markmap-cli/dist/index.js:14898:16)
    at loadLanguages (/usr/local/lib/node_modules/markmap-cli/dist/index.js:14941:51)
    at Function.highlight (/usr/local/lib/node_modules/markmap-cli/dist/index.js:15083:11)
    at Object.rules.fence (/usr/local/lib/node_modules/markmap-cli/dist/index.js:2537:37)
    at Renderer.render (/usr/local/lib/node_modules/markmap-cli/dist/index.js:3066:39)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12803) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:12803) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by VaguelyCloud** [comment]
I found a solution, add prismjs into the model folder, and then inject the following code into index.js。
var Prism = require('prismjs');
var loadLanguages = require('prismjs/components/');

**Comment by gera2ld** [comment]
Fixed in d958166, v0.5.3
